def introduction():
    print("welcome to the personl information program.")
    print("Hello, i would to get to know a little about you")
    print()
    print("please answer a few brief questions")
    print()
    Print("What is your name?")
    name = input()
    print()
    print(f"{name}, what college are you attending?")
    college = input()
    print()
    print(f"{name},Which institution is more fun? (College/High School)")
    institution = input()
    print()
    print("what is your favorite subject")
    favorite_subject = input()
    print()
    print("What is your favorite hobby?")
    favorite_hobby = input()
    print()
    return name, college, high_school, institution
def main():
    print(f"\nIt was nice to speak with you, {name}.")
    print()
    print(f"\nYou are currenlt attending, {name}.")
    print()
    print(f"\nI learned that your high school's name is {high_school}")
    print()
    print("it was fun getting to know a little about you.")
    print()
    print("Let's do this again!")
if __name__ == "__main__":
    main()
